[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
src_dir = flix
monitor_speed = 115200
build_flags =
    -D ESP32C3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    FlixPeriph
    mavlink/MAVLink@2.0.25
