[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

src_dir = flix

lib_deps =
    https://github.com/okalachev/flixperiph.git
    https://github.com/mavlink/c_library_v2.git
    https://github.com/bolderflight/sbus-arduino.git
